name: Milvus2 Node sdk check when open pr

on:
  pull_request:
    branches:
      - main
    types: [opened]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run Milvus
        run: |
          wget https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml
          docker-compose up -d

      - name: Run Test coverage
        run: |
          yarn
          yarn build-test
          yarn coverage
